services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    volumes:
      - ./app:/flask/app
    depends_on:
      - database
    networks:
      - network
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: mydatabase

  database:
    image: mysql:8.3
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network

volumes:
  mysql_data:

networks:
  network:
    driver: bridge
