services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    volumes:
      - ./app:/app 
    environment:
      - FLASK_APP=app:create_app 
      - DATABASE_HOST=database
      - DATABASE_USER=user
      - DATABASE_PASSWORD=userpassword
      - DATABASE_NAME=mydatabase
    depends_on:
      - database

  database:
    image: mysql:8.3
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: